server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: carSales
          uri: http://localhost:8081
          predicates:
            - Path=/carSaleses/** 
        - id: inspection
          uri: http://localhost:8082
          predicates:
            - Path=/inspections/** 
        - id: insurance
          uri: http://localhost:8083
          predicates:
            - Path=/insurances/** 
        - id: dashboard
          uri: http://localhost:8084
          predicates:
            - Path=/salesStatuses/** 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: carsales2
          uri: http://carsales2:8080
          predicates:
            - Path=/carSaleses/**  
        - id: inspection2
          uri: http://inspection2:8080
          predicates:
            - Path=/inspections/** 
        - id: insurance2
          uri: http://insurance2:8080
          predicates:
            - Path=/insurances/** 
        - id: dashboard2
          uri: http://dashboard2:8080
          predicates:
            - Path=/salesStatuses/** 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
